### ISSUE TITLE
Ordered list should default to Hindu-Arabic

### ISSUE THREAD

**Issue by rajinder-yadav** [1000ch/node-github-markdown#12]
I am seeing two flavors both of which don't make sense, images attached.

Single nested order list show roman numerals (should default to Hindu-Arabic).

**IMAGE ONE**
![nest1](https://cloud.githubusercontent.com/assets/439226/18812041/1cad7b38-8295-11e6-9d4c-0d8728f81c0b.png)

Double nested order list show letters (should default to Hindu-Arabic).

**IMAGE TWO**
![nest2](https://cloud.githubusercontent.com/assets/439226/18812046/521634ae-8295-11e6-8193-81cb9fd7c3f7.png)

**Comment by error418** [comment]
Since this is the way Github renders these kind of lists I don't know why the output of the program should be different. Am I overseeing something?

**Comment by rajinder-yadav** [comment]
I have no idea, I've been writing markdown a lot on Github and when I was using this module the output was different. I've since switch to something else, so you will have to try various order lists and compare the outputs.

**Comment by error418** [comment]
According to the `primer-css` documentation the behaviour of the application is correct. (The generated HTMLs are using the `primer-css` styles, which are the same Github is using)

See http://primercss.io/type/#ordered for more details

I think the issue can be closed

**Comment by rajinder-yadav** [comment]
Are you using a css styling file? Before you close, compare the resulting html file with the same markdown posted on github, if they look identical I would close the issue.

Make sure to use ordered list as well has nested order list.

**Comment by error418** [comment]
Edited my last comment to add the responsible classes of `primer-css`

```css
ol ol,ul ol {
    list-style-type:lower-roman
}

ul ul ol,ul ol ol,ol ul ol,ol ol ol {
    list-style-type:lower-alpha
}
```

**Comment by rajinder-yadav** [comment]
OK Cool, just verified quickly, you can close.

**Comment by error418** [comment]
Thanks for verifying :)
Can you please close the issue? (I am only a contributor of this project)

**Comment by rajinder-yadav** [comment]
Sure thing!
