### ISSUE TITLE
Version argument

### ISSUE THREAD

**Issue by funkill** [1000ch/node-github-markdown#7]
Print version of ghmd on some argument, e.g. `-v`, `-V` or `--version`:

```bash
$ ghmd --version
github-markdown v1.0.0
```

Grunt use `-V` and `--version` (but `-v` for verbose), bower: `--version` (but `-V` for verbose), less: `-v` and `--version` They print:

```bash
$ grunt -V
grunt-cli v0.1.13
grunt v0.4.5
$ bower --version
1.4.1
$ lessc -v
lessc 2.5.0 (Less Compiler) [JavaScript]
```

**Comment by funkill** [comment]
Bower also used `-v` for version, but i don't find it argument in help message

**Comment by 1000ch** [comment]
`-v` or `--version` option will out package version.
